package uz.androdev.memorization.ui.theme

import androidx.compose.ui.graphics.Color

val memorizationLightPrimary = Color(0xFF825500)
val memorizationLightOnPrimary = Color(0xFFFFFFFF)
val memorizationLightPrimaryContainer = Color(0xFFFFDDAE)
val memorizationLightOnPrimaryContainer = Color(0xFF2A1800)
val memorizationLightSecondary = Color(0xFF6F5B40)
val memorizationLightOnSecondary = Color(0xFFFFFFFF)
val memorizationLightSecondaryContainer = Color(0xFFFADEBC)
val memorizationLightOnSecondaryContainer = Color(0xFF271904)
val memorizationLightTertiary = Color(0xFF516440)
val memorizationLightOnTertiary = Color(0xFFFFFFFF)
val memorizationLightTertiaryContainer = Color(0xFFD3EABC)
val memorizationLightOnTertiaryContainer = Color(0xFF102004)
val memorizationLightError = Color(0xFFBA1B1B)
val memorizationLightErrorContainer = Color(0xFFFFDAD4)
val memorizationLightOnError = Color(0xFFFFFFFF)
val memorizationLightOnErrorContainer = Color(0xFF410001)
val memorizationLightBackground = Color(0xFFFCFCFC)
val memorizationLightOnBackground = Color(0xFF1F1B16)
val memorizationLightSurface = Color(0xFFFCFCFC)
val memorizationLightOnSurface = Color(0xFF1F1B16)
val memorizationLightSurfaceVariant = Color(0xFFF0E0CF)
val memorizationLightOnSurfaceVariant = Color(0xFF4F4539)
val memorizationLightOutline = Color(0xFF817567)
val memorizationLightInverseOnSurface = Color(0xFFF9EFE6)
val memorizationLightInverseSurface = Color(0xFF34302A)
val memorizationLightPrimaryInverse = Color(0xFFFFB945)

val memorizationDarkPrimary = Color(0xFFFFB945)
val memorizationDarkOnPrimary = Color(0xFF452B00)
val memorizationDarkPrimaryContainer = Color(0xFF624000)
val memorizationDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val memorizationDarkSecondary = Color(0xFFDDC3A2)
val memorizationDarkOnSecondary = Color(0xFF3E2E16)
val memorizationDarkSecondaryContainer = Color(0xFF56442B)
val memorizationDarkOnSecondaryContainer = Color(0xFFFADEBC)
val memorizationDarkTertiary = Color(0xFFB8CEA2)
val memorizationDarkOnTertiary = Color(0xFF243516)
val memorizationDarkTertiaryContainer = Color(0xFF3A4C2B)
val memorizationDarkOnTertiaryContainer = Color(0xFFD3EABC)
val memorizationDarkError = Color(0xFFFFB4A9)
val memorizationDarkErrorContainer = Color(0xFF930006)
val memorizationDarkOnError = Color(0xFF680003)
val memorizationDarkOnErrorContainer = Color(0xFFFFDAD4)
val memorizationDarkBackground = Color(0xFF1F1B16)
val memorizationDarkOnBackground = Color(0xFFEAE1D9)
val memorizationDarkSurface = Color(0xFF1F1B16)
val memorizationDarkOnSurface = Color(0xFFEAE1D9)
val memorizationDarkSurfaceVariant = Color(0xFF4F4539)
val memorizationDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val memorizationDarkOutline = Color(0xFF9C8F80)
val memorizationDarkInverseOnSurface = Color(0xFF32281A)
val memorizationDarkInverseSurface = Color(0xFFEAE1D9)
val memorizationDarkPrimaryInverse = Color(0xFF624000)